version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-74
  brakeman:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
exclude_patterns:
- spec/**/*
- "**/vendor/**/*"
- rest/connection.rb
- core_extensions/string/json_to_hash.rb
