language: ruby
cache: bundler
rvm:
  - 2.4.2
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
  - gem --version
  - gem install bundler
  - bundler --version
script:
  - bundle exec rspec
notifications:
  email: false
  slack: financialapps:fA8XwEcap3hHZk0iNmPPJvT1
addons:
  code_climate:
    repo_token: 5a8d194cbc23aa4c171e3478e3b6bbea9dd96041071380ec25bf80c07770b39a
after_success:
  - bundle exec codeclimate-test-reporter