language: ruby
os: ["linux"]
dist: "xenial"

cache:
  bundler: true

rvm:
  - 2.6

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem install bundler --force --quiet

script:
  - bundle exec rspec

notifications:
  email: false
  slack: financialapps:fA8XwEcap3hHZk0iNmPPJvT1
addons:
  code_climate:
    repo_token: 5a8d194cbc23aa4c171e3478e3b6bbea9dd96041071380ec25bf80c07770b39a
after_success:
  - bundle exec codeclimate-test-reporter
