name: Continuous Integration

on: 
  push: 
    paths-ignore:
      - ".github/**"
      - ".VERSION"
  pull_request:
    paths-ignore:
      - ".github/**"
      - ".VERSION"
jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install required ruby version
        uses: ruby/setup-ruby@v1

      - name: Setup cache key and directory for gems cache
        uses: actions/cache@v2.1.4
        with:
          path: vendor/bundle
          key: ${{ runner.os  }}-gems-${{ hashFiles('**/Gemfile.lock')  }}
          restore-keys: |
            ${{ runner.os  }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle config set jobs 4
          bundle config set retry 3
          bundle install

      - name: Run rubocop
        run: |
          bundle exec rubocop --parallel

      - name: Run rspec with coverage
        run: |
          COVERAGE=true bundle exec rspec

      - name: Run Skunk on Project
        run: |
          gem install skunk
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$CURRENT_BRANCH" != "master" ]]; then
            echo "Executing within branch: $CURRENT_BRANCH"
            skunk lib/ -b master
          else
            echo "Executing within master branch"
            skunk lib/
          fi
